# PyTorch Tensor Creation — Categorized Notes

This notebook reorganizes the tensor-creation material from the original **Tensors_in_pytorch.ipynb** into a clear teaching hierarchy.

The main idea is to classify tensor creation by **where the values come from or how the tensor is initialized**.

> **Teaching pattern:** One main category → sub-category → one focused code cell.
>
> Code cells are saved in a collapsed state so that they can be opened only when needed during teaching.


## Table of Contents

1. **Tensor Creation**
   - 1.1 From Existing Data
     - `torch.tensor()`
     - `torch.Tensor()`
     - `torch.from_numpy()`
   - 1.2 Constant / Initialized Tensors
     - `torch.zeros()`
     - `torch.ones()`
     - `torch.full()`
   - 1.3 Uninitialized Tensors
     - `torch.empty()`
   - 1.4 Sequence-Based Tensors
     - `torch.arange()`
     - `torch.linspace()`
   - 1.5 Special-Pattern Tensors
     - `torch.eye()`
   - 1.6 Random Tensors
     - `torch.rand()`
     - `torch.randn()`
     - `torch.randint()`
   - 1.7 Tensor Creation Based on an Existing Tensor
     - `torch.empty_like()`
     - `torch.zeros_like()`
     - `torch.ones_like()`
     - `torch.rand_like()`
     - `torch.full_like()`
2. **Quick Classification Table**
3. **Important Teaching Points**


# 1. Tensor Creation

A tensor can be created in different ways. A useful classification is:

| Main Category | Sub-category | Functions |
|---|---|---|
| **1. Existing Data** | Python data | `torch.tensor()` |
| | PyTorch tensor constructor | `torch.Tensor()` |
| | NumPy data | `torch.from_numpy()` |
| **2. Constant / Initialized** | All zeros | `torch.zeros()` |
| | All ones | `torch.ones()` |
| | Same constant value | `torch.full()` |
| **3. Uninitialized** | Allocate memory only | `torch.empty()` |
| **4. Sequence-Based** | Fixed step | `torch.arange()` |
| | Fixed number of values | `torch.linspace()` |
| **5. Special Pattern** | Identity matrix | `torch.eye()` |
| **6. Random** | Uniform [0, 1) | `torch.rand()` |
| | Normal distribution | `torch.randn()` |
| | Random integers | `torch.randint()` |
| **7. Based on Existing Tensor** | Same shape/properties | `*_like()` functions |


## 1.1 From Existing Data

When values already exist in Python or another data structure, we can convert them into a PyTorch tensor.


### 1.1.1 `torch.tensor()` — From Python List / Tuple

`torch.tensor()` creates a new tensor from existing Python data such as a list or tuple.


In [3]:
import torch

my_list = [[1, 2, 3], [4, 5, 6]]

x = torch.tensor(my_list)

print(x)
print("Shape:", x.shape)
print("dtype:", x.dtype)
print("Type :", type(x))


tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
dtype: torch.int64
Type : <class 'torch.Tensor'>


### 1.1.2 `torch.Tensor()` — Tensor Constructor

`torch.Tensor()` can also construct a tensor. For modern PyTorch code, prefer the explicit factory `torch.tensor()` when converting existing data.


In [4]:
x = torch.Tensor([1, 2, 3])

print(x)
print("dtype:", x.dtype)
print("Type :", type(x))


tensor([1., 2., 3.])
dtype: torch.float32
Type : <class 'torch.Tensor'>


### 1.1.3 `torch.from_numpy()` — From NumPy Array

`torch.from_numpy()` creates a tensor from a NumPy array. The tensor and NumPy array generally share the same memory.


In [5]:
import numpy as np

arr = np.array([1, 2, 3])

x = torch.from_numpy(arr)

print("NumPy array:", arr)
print("Tensor:", x)


NumPy array: [1 2 3]
Tensor: tensor([1, 2, 3])


## 1.2 Constant / Initialized Tensors

These functions create tensors whose elements are initialized to a known value.


### 1.2.1 `torch.zeros()` — All Zeros

Use `torch.zeros(shape)` when every element should initially be zero.


In [6]:
x = torch.zeros(2, 3)

print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 1.2.2 `torch.ones()` — All Ones

Use `torch.ones(shape)` when every element should initially be one.


In [ ]:
x = torch.ones(2, 3)

print(x)


### 1.2.3 `torch.full()` — Same User-Defined Value

Use `torch.full(shape, fill_value)` when every element should contain a particular value.


In [7]:
x = torch.full((2, 3), 5)

print(x)


tensor([[5, 5, 5],
        [5, 5, 5]])


## 1.3 Uninitialized Tensors

### 1.3.1 `torch.empty()` — Memory Is Allocated, Values Are Not Initialized

`torch.empty()` creates a tensor without initializing its elements to zero or another predictable value.

The displayed values should **not** be interpreted as meaningful data.


In [8]:
x = torch.empty(2, 3)

print(x)


tensor([[4.2319e+09, 4.3827e-41, 4.2319e+09],
        [4.3827e-41, 0.0000e+00, 0.0000e+00]])


## 1.4 Sequence-Based Tensors

These functions generate values following a numerical sequence.


### 1.4.1 `torch.arange()` — Start, End, Step

`torch.arange(start, end, step)` generates values using a step size. The `end` value is normally excluded.

Conceptually:

`start → start + step → start + 2×step → ...`


In [ ]:
x = torch.arange(0, 10, 2)

print(x)


### 1.4.2 `torch.linspace()` — Start, End, Number of Values

`torch.linspace(start, end, steps)` generates a specified number of equally spaced values between `start` and `end`.

The important difference is:

- `arange()` → you specify the **step**
- `linspace()` → you specify the **number of values**


In [ ]:
x = torch.linspace(0, 10, 6)

print(x)


## 1.5 Special-Pattern Tensors

### 1.5.1 `torch.eye()` — Identity Matrix

`torch.eye(n)` creates a square identity matrix with ones on the main diagonal and zeros elsewhere.


In [9]:
x = torch.eye(4)

print(x)


tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


## 1.6 Random Tensors

Random tensors are especially important in deep learning for initialization, experiments, sampling, and testing.


### 1.6.1 `torch.rand()` — Uniform Random Values

`torch.rand()` generates random floating-point values from a uniform distribution over approximately `[0, 1)`.


In [ ]:
torch.manual_seed(100)

x = torch.rand(2, 3)

print(x)


### 1.6.2 `torch.randn()` — Standard Normal Distribution

`torch.randn()` generates random values from a normal distribution with approximately:

- mean = 0
- standard deviation = 1


In [ ]:
torch.manual_seed(100)

x = torch.randn(2, 3)

print(x)


### 1.6.3 `torch.randint()` — Random Integers

`torch.randint(low, high, size)` generates random integers from `low` (inclusive) to `high` (exclusive).


In [ ]:
torch.manual_seed(100)

x = torch.randint(1, 10, (2, 3))

print(x)


### 1.6.4 `torch.manual_seed()` — Reproducible Random Values

A random tensor changes from run to run unless a seed is controlled.

Resetting the same seed reproduces the same random sequence.


In [ ]:
torch.manual_seed(100)
x1 = torch.rand(2, 3)

torch.manual_seed(100)
x2 = torch.rand(2, 3)

print("x1:")
print(x1)


print("\nx2:")
print(x2)

print("\nAre they equal?", torch.equal(x1, x2))


## 1.7 Tensor Creation Based on an Existing Tensor

The `*_like()` family creates a new tensor using an existing tensor as the reference.

The main benefit is that the new tensor can inherit properties such as shape and, where appropriate, dtype/device.


### 1.7.1 `torch.empty_like()` — Same Shape, Uninitialized

Creates an uninitialized tensor with the same shape as the reference tensor.


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

y = torch.empty_like(x)

print("Original x:")
print(x)

print("\nempty_like(x):")
print(y)


### 1.7.2 `torch.zeros_like()` — Same Shape, All Zeros

Creates a tensor with the same shape as the reference tensor, filled with zeros.


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

y = torch.zeros_like(x)

print(y)


### 1.7.3 `torch.ones_like()` — Same Shape, All Ones

Creates a tensor with the same shape as the reference tensor, filled with ones.


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

y = torch.ones_like(x)

print(y)


### 1.7.4 `torch.rand_like()` — Same Shape, Random Values

Creates a random tensor using the shape of an existing tensor.


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

y = torch.rand_like(x, dtype=torch.float32)

print(y)


### 1.7.5 `torch.full_like()` — Same Shape, Same User-Defined Value

Creates a tensor with the same shape as the reference tensor and fills it with a chosen value.


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])

y = torch.full_like(x, 7)

print(y)


# 2. Quick Classification Table

Use this table as the final revision sheet.

| Category | Question to Ask | Function |
|---|---|---|
| **Existing Data** | Do I already have the values? | `torch.tensor()` |
| | Is the existing data a NumPy array? | `torch.from_numpy()` |
| **Constant / Initialized** | Do I want all values = 0? | `torch.zeros()` |
| | Do I want all values = 1? | `torch.ones()` |
| | Do I want all values = some value? | `torch.full()` |
| **Uninitialized** | Do I only need allocated memory? | `torch.empty()` |
| **Sequence** | Do I want a sequence with a step? | `torch.arange()` |
| | Do I want equally spaced values with a fixed count? | `torch.linspace()` |
| **Special Pattern** | Do I want an identity matrix? | `torch.eye()` |
| **Random** | Random floats between 0 and 1? | `torch.rand()` |
| | Random values from normal distribution? | `torch.randn()` |
| | Random integers? | `torch.randint()` |
| **Existing Tensor as Template** | Same shape, but empty? | `torch.empty_like()` |
| | Same shape, all zeros? | `torch.zeros_like()` |
| | Same shape, all ones? | `torch.ones_like()` |
| | Same shape, random values? | `torch.rand_like()` |
| | Same shape, chosen value? | `torch.full_like()` |


# 3. Important Teaching Points

### 3.1 `arange()` vs `linspace()`

```text
arange()   → start, end, step
linspace() → start, end, number of values
```

### 3.2 `zeros()` / `ones()` / `full()`

```text
zeros() → fill with 0
ones()  → fill with 1
full()  → fill with any chosen value
```

### 3.3 Normal vs Uniform Random Values

```text
rand()  → uniform distribution
randn() → normal distribution
```

### 3.4 Normal creation vs `*_like()` creation

```text
torch.zeros(2, 3)
        ↓
You specify the shape.

torch.zeros_like(x)
        ↓
The existing tensor x provides the shape/reference.
```

### 3.5 Important distinction

`torch.empty()` does **not** mean "empty tensor with no elements".

It means:

> **Memory is allocated, but the elements are not initialized to a known value.**


# 4. One-Page Mental Map

```text
TENSOR CREATION
│
├── 1. Existing Data
│   ├── torch.tensor()
│   ├── torch.Tensor()
│   └── torch.from_numpy()
│
├── 2. Constant / Initialized
│   ├── torch.zeros()
│   ├── torch.ones()
│   └── torch.full()
│
├── 3. Uninitialized
│   └── torch.empty()
│
├── 4. Sequence-Based
│   ├── torch.arange()
│   └── torch.linspace()
│
├── 5. Special Pattern
│   └── torch.eye()
│
├── 6. Random
│   ├── torch.rand()
│   ├── torch.randn()
│   └── torch.randint()
│
└── 7. Based on Existing Tensor
    ├── torch.empty_like()
    ├── torch.zeros_like()
    ├── torch.ones_like()
    ├── torch.rand_like()
    └── torch.full_like()
```

This hierarchy is intended to make the notebook easy to navigate while teaching: **main category → subheading → one focused code cell**.
