# PyTorch `nn` Module for Complete Beginners

## Learning Goals
By the end of this notebook, you will understand:

1. What is `torch.nn`
2. Why we use `nn.Module`
3. How to create a neural network class
4. What is a Linear Layer
5. What is an Activation Function
6. How the Forward Pass works
7. How to use `nn.Sequential`
8. How to use Built-in Loss Functions
9. How to use Optimizers (`torch.optim`)

This notebook is based on the lecture transcript provided by the user. fileciteturn0file0


In [1]:
import torch
import torch.nn as nn

print("PyTorch Version:", torch.__version__)


PyTorch Version: 2.11.0+cu128


# 1. Why do we need the `nn` module?

Before `torch.nn`, we would manually create:

- Weights
- Biases
- Activation Functions
- Loss Functions
- Parameter Update Logic

For large neural networks, this becomes difficult.

`torch.nn` provides ready-made building blocks.

## Mathematical Idea

A neuron computes:

$$
z = w_1x_1 + w_2x_2 + ... + w_nx_n + b
$$

Then an activation function is applied:

$$
\hat{y} = f(z)
$$


In [ ]:
# Nothing to run here.
# Just remember the neuron equation.


# 2. Important Components Inside `torch.nn`

Commonly used components:

| Component | Example |
|------------|----------|
| Layers | nn.Linear |
| Activations | nn.ReLU, nn.Sigmoid |
| Loss Functions | nn.BCELoss, nn.CrossEntropyLoss |
| Containers | nn.Sequential |
| Utilities | Dropout, BatchNorm |

Think of `torch.nn` as a toolbox for building neural networks.


In [2]:
import torch.nn as nn

print("Linear Layer :", nn.Linear)
print("Sigmoid      :", nn.Sigmoid)
print("ReLU         :", nn.ReLU)
print("BCELoss      :", nn.BCELoss)


Linear Layer : <class 'torch.nn.modules.linear.Linear'>
Sigmoid      : <class 'torch.nn.modules.activation.Sigmoid'>
ReLU         : <class 'torch.nn.modules.activation.ReLU'>
BCELoss      : <class 'torch.nn.modules.loss.BCELoss'>


# 3. Our First Neural Network

We will build:

- 5 input features
- 1 output neuron
- Sigmoid activation

Architecture:

Input(5) → Linear → Sigmoid → Output(1)

## Equation

$$
z = Wx + b
$$

$$
\hat y = sigmoid(z)
$$


In [3]:
import torch
import torch.nn as nn

class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()

        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):

        out = self.linear(x)
        out = self.sigmoid(out)

        return out


# 4. Understanding `super().__init__()` and our class Model

Our class inherits from:

```python
nn.Module
```

Therefore:

```python
super().__init__()
```

calls the constructor of the parent class.

Without this line, PyTorch cannot properly register layers and parameters.


In [ ]:
# No execution needed.
# This is a theory section.


Here's how the `Model` class reflects the architecture and mathematical idea:

*   **`__init__(self, num_features)`**: This method is the constructor where we *define* the layers (building blocks) of our neural network. It's like setting up the blueprint.
    *   **`super().__init__()`**: Calls the constructor of the parent class `nn.Module` to ensure proper initialization.
    *   **`self.linear = nn.Linear(num_features, 1)`**: This creates an instance of a linear layer. At this stage, you are *initializing* the layer, which includes creating its learnable parameters (weights `W` and biases `b`). The calculation `z = Wx + b` *does not happen yet*.
    *   **`self.sigmoid = nn.Sigmoid()`**: This creates an instance of the sigmoid activation function.

*   **`forward(self, x)`**: This method defines the forward pass, i.e., how the input `x` flows through the network to produce an output. This is where the *actual calculations* happen.
    *   **`out = self.linear(x)`**: **This is where the calculation `z = Wx + b` actually occurs!** When you call `self.linear(x)`, you are passing the input `x` through the `linear` layer's internal `forward` method, which performs the matrix multiplication of `x` with `W` and adds the bias `b` to produce `z`.
    *   **`out = self.sigmoid(out)`**: The result `z` from the linear layer is then passed through the `sigmoid` activation function. This step corresponds to `y_pred = sigmoid(z)`.
    *   **`return out`**: The final predicted output `y_pred` is returned.

# 5. Create the Model Object

We now create an object of our model.

Input features = 5


In [4]:
# Creating the Architecture and intiating the object of the class
model = Model(num_features=5)

print("Model Architecture")
print("*",50*"=")
print(model)
print("*",50*"-")
print(model.linear)
print("*",50*"-")
print(model.linear.weight)
print("*",50*"-")
print(model.linear.bias)

Model Architecture
* ==================================================
Model(
  (linear): Linear(in_features=5, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)
* --------------------------------------------------
Linear(in_features=5, out_features=1, bias=True)
* --------------------------------------------------
Parameter containing:
tensor([[-0.0508, -0.0456,  0.2536,  0.3767,  0.1904]], requires_grad=True)
* --------------------------------------------------
Parameter containing:
tensor([0.4456], requires_grad=True)


# 6. Create Dummy Data

We create:

- 10 rows
- 5 features

Shape:

$$
(10,5)
$$


In [5]:
features = torch.randn(10, 5)

print(features.shape)
features


torch.Size([10, 5])


tensor([[-8.9918e-01, -1.2687e-01,  1.3045e-01,  2.8505e+00,  5.9101e-01],
        [ 3.0393e-01,  1.5951e+00,  6.9631e-02,  1.0709e+00, -4.9336e-01],
        [ 1.3148e+00,  1.3755e+00,  4.5997e-01, -2.7813e-01, -1.2025e+00],
        [ 3.9788e-01,  4.2039e-01,  2.6241e+00, -1.4181e+00,  1.5994e-01],
        [ 3.6130e-01, -1.4796e+00,  6.1846e-01,  2.1156e+00, -8.7072e-01],
        [-6.2534e-01,  7.2897e-01,  1.2256e+00,  7.0762e-01, -2.8889e-01],
        [-1.1947e-01,  7.3129e-01,  1.7083e+00,  9.9542e-01,  1.0213e-01],
        [-1.1512e+00, -1.9426e-01, -2.1148e-03, -4.1986e-01,  1.0818e+00],
        [ 3.9897e-02, -1.6631e-01,  1.1973e-01,  1.2556e+00,  7.3106e-01],
        [-1.2496e-01, -2.0785e-01, -1.9555e+00, -4.1707e-01,  1.3262e-01]])

# 7. Forward Pass

Instead of:

```python
model.forward(features)
```

PyTorch recommends:

```python
model(features)
```

Internally PyTorch automatically calls the `forward()` method.


In [6]:
predictions = model(features)

print(predictions.shape)
predictions[:5]


torch.Size([10, 1])


tensor([[0.8477],
        [0.6647],
        [0.5247],
        [0.6382],
        [0.7829]], grad_fn=<SliceBackward0>)

## Forward Pass: What Happens Inside `model(features)`?

When we execute:

```python
predictions = model(features)
```

PyTorch automatically calls:

```python
model.forward(features)
```

Inside the model, the first operation is:

```python
z = self.linear(features)
```

Mathematically:

$$
Z = XW^T + b
$$

where

$$
X =
\begin{bmatrix}
x_{11} & x_{12} & x_{13} & x_{14} & x_{15} \\
x_{21} & x_{22} & x_{23} & x_{24} & x_{25} \\
\vdots & \vdots & \vdots & \vdots & \vdots \\
x_{10,1} & x_{10,2} & x_{10,3} & x_{10,4} & x_{10,5}
\end{bmatrix}
$$

Shape:

$$
(10 \times 5)
$$

The weight matrix learned by the model is:

$$
W =
\begin{bmatrix}
w_1 & w_2 & w_3 & w_4 & w_5
\end{bmatrix}
$$

Shape:

$$
(1 \times 5)
$$

PyTorch internally uses:

$$
W^T =
\begin{bmatrix}
w_1\\
w_2\\
w_3\\
w_4\\
w_5
\end{bmatrix}
$$

Shape:

$$
(5 \times 1)
$$

Therefore:

$$
(10 \times 5)
\times
(5 \times 1)
=
(10 \times 1)
$$

The matrix multiplication becomes:

$$
\begin{bmatrix}
x_{11} & x_{12} & x_{13} & x_{14} & x_{15}\\
x_{21} & x_{22} & x_{23} & x_{24} & x_{25}\\
\vdots & \vdots & \vdots & \vdots & \vdots\\
x_{10,1} & x_{10,2} & x_{10,3} & x_{10,4} & x_{10,5}
\end{bmatrix}
\times
\begin{bmatrix}
w_1\\
w_2\\
w_3\\
w_4\\
w_5
\end{bmatrix}
+
b
$$

Result:

$$
Z =
\begin{bmatrix}
z_1\\
z_2\\
\vdots\\
z_{10}
\end{bmatrix}
$$

Shape:

$$
(10 \times 1)
$$

Each output is calculated as:

$$
z_i =
w_1x_{i1}
+
w_2x_{i2}
+
w_3x_{i3}
+
w_4x_{i4}
+
w_5x_{i5}
+
b
$$

Next, the Sigmoid activation function is applied:

$$
\hat y =
\sigma(z)
=
\frac{1}{1+e^{-z}}
$$

Therefore:

$$
Predictions =
\sigma(XW^T+b)
$$

Final output shape:

$$
(10 \times 1)
$$

This is exactly why:

```python
print(predictions.shape)
```

produces:

```python
torch.Size([10,1])
```

# 8. Viewing Weights and Bias

Every Linear Layer contains:

- Weights
- Bias

For 5 input features and 1 output neuron:

Weights shape:

$$
(1,5)
$$

Bias shape:

$$
(1)
$$


In [ ]:
print("Weights")
print(model.linear.weight)

print("\nBias")
print(model.linear.bias)


# 9. Multi-Layer Neural Network

Now we build:

Input(5)
→ Hidden Layer(3 neurons)
→ ReLU
→ Output Layer(1 neuron)
→ Sigmoid

## Parameters

First Layer:

$$
5 \times 3 = 15
$$

Second Layer:

$$
3 \times 1 = 3
$$

Total weights:

$$
18
$$

Biases:

$$
3 + 1 = 4
$$


In [ ]:
class DeepModel(nn.Module):

    def __init__(self, num_features):

        super().__init__()

        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()

        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):

        out = self.linear1(x)
        out = self.relu(out)

        out = self.linear2(out)
        out = self.sigmoid(out)

        return out


# 10. Test the Multi-Layer Model


In [ ]:
deep_model = DeepModel(5)

output = deep_model(features)

print(output.shape)
# output[:5]


In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(deep_model, input_size=(1,5))

In [ ]:
# Weights and biases of each layers with shape

for name, param in deep_model.named_parameters():
    print(name, param.shape)



# 11. Why `nn.Sequential`?

When networks become larger, writing:

```python
out = layer1(x)
out = relu(out)
out = layer2(out)
...
```

becomes repetitive.

`nn.Sequential` automatically chains layers together.


In [ ]:
class SequentialModel(nn.Module):

    def __init__(self, num_features):

        super().__init__()

        self.network1 = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.network1(x)


# 12. Run the Sequential Model


In [ ]:
seq_model = SequentialModel(5)

preds = seq_model(features)

print(preds.shape)
preds[:5]


In [ ]:
from torchinfo import summary

summary(seq_model, input_size=(1,5))

# 13. Binary Classification Loss

For binary classification we often use:

```python
nn.BCELoss()
```

Mathematical Formula:

$$
Loss = -[y\log(\hat y)+(1-y)\log(1-\hat y)]
$$

Lower loss means better predictions.


In [ ]:
loss_function = nn.BCELoss()

print(loss_function)


# 14. Create Target Labels


In [ ]:
y_train = torch.randint(0, 2, (10,1)).float()

print(y_train)


# 15. Calculate Loss


In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Ensure the model is on the correct device
seq_model = seq_model.to(device)

# Ensure the input features are on the correct device
features = features.to(device)

# Ensure the target labels are on the correct device
y_train = y_train.to(device)

preds = seq_model(features)

loss = loss_function(preds, y_train)

print("Loss =", loss.item())

In [ ]:
preds.shape , y_train.shape

# 16. Backpropagation

PyTorch calculates gradients automatically.

Steps:

1. Forward Pass
2. Compute Loss
3. Backward Pass

```python
loss.backward()
```


In [ ]:
loss.backward()

print("Gradient of first layer weights")
print(seq_model.network1[0].weight.grad)

print("\nGradient of first layer bias")
print(seq_model.network1[0].bias.grad)

print("$"*50)

print("\nGradient of second layer weights")
print(seq_model.network1[2].weight.grad)

print("\nGradient of second layer bias")
print(seq_model.network1[2].bias.grad)


# 17. Optimizers

Instead of manually updating:

$$
w = w - \eta \frac{\partial L}{\partial w}
$$

we use an optimizer.

Most common:

```python
torch.optim.SGD
```


In [ ]:
optimizer = torch.optim.SGD(seq_model.parameters(),lr=0.01)

print(optimizer)


# 18. Understanding `model.parameters()`

This function returns all trainable parameters:

- Weights
- Biases

PyTorch automatically registers them.


In [ ]:
for parameter in seq_model.parameters():
    print(parameter.shape)


# 19. Full Training Loop

Standard PyTorch Training Flow:

```text
Zero Gradients
      ↓
Forward Pass
      ↓
Loss Calculation
      ↓
Backward Pass
      ↓
Optimizer Step
```


In [ ]:
for epoch in range(5):

    optimizer.zero_grad()

    predictions = seq_model(features)

    loss = loss_function(predictions, y_train)

    loss.backward()

    optimizer.step()

    print(f"Epoch {epoch+1}: Loss = {loss.item():.4f}")


# 20. Final Summary

## What we learned

### torch.nn

- nn.Module
- nn.Linear
- nn.ReLU
- nn.Sigmoid
- nn.BCELoss
- nn.Sequential

### torch.optim

- SGD Optimizer
- optimizer.step()
- optimizer.zero_grad()

### Neural Network Workflow

Data
→ Model
→ Forward Pass
→ Loss
→ Backward Pass
→ Optimizer Step

This is the foundation of almost every PyTorch deep learning project.


```text
X → Z₁ = XW₁ᵀ + b₁ → A₁ = ReLU(Z₁) → Z₂ = A₁W₂ᵀ + b₂ → ŷ = Sigmoid(Z₂) → L = BCE(ŷ,y) → {∂L/∂W₂, ∂L/∂b₂, ∂L/∂W₁, ∂L/∂b₁} → SGD → Updated {W₁,b₁,W₂,b₂}
```