# PyTorch Fundamentals: A Comprehensive Guide

This notebook covers the fundamental concepts of PyTorch, from tensor creation and manipulation to various mathematical operations and tensor copying.

## Table of Contents

1.  [Introduction to PyTorch](#introduction-to-pytorch)
    -   [Environment Setup](#environment-setup)
2.  [Creating Tensors](#creating-tensors)
    -   [Initializing Tensors](#initializing-tensors)
    -   [Creating Tensors from Data](#creating-tensors-from-data)
    -   [Specialized Tensor Creation Functions](#specialized-tensor-creation-functions)
3.  [Tensor Shapes](#tensor-shapes)
    -   [Inspecting Shape](#inspecting-shape)
    -   [Creating Tensors with Similar Shapes](#creating-tensors-with-similar-shapes)
4.  [Tensor Data Types](#tensor-data-types)
    -   [Checking and Assigning Data Types](#checking-and-assigning-data-types)
    -   [Detailed Data Type Reference](#detailed-data-type-reference)
5.  [Mathematical Operations](#mathematical-operations)
    -   [Scalar Operations](#scalar-operations)
    -   [Element-Wise Operations](#element-wise-operations)
    -   [Reduction Operations](#reduction-operations)
    -   [Matrix Operations](#matrix-operations)
    -   [Comparison Operations](#comparison-operations)
    -   [Special Functions](#special-functions)
6.  [Inplace Operations](#inplace-operations)
7.  [Copying a Tensor](#copying-a-tensor)

## 1. Introduction to PyTorch

PyTorch is an open-source machine learning library primarily developed by Facebook's AI Research lab (FAIR). It's widely used for deep learning applications due to its flexibility, dynamic computation graph, and strong GPU acceleration.



### Environment Setup

Before diving into PyTorch, it's good practice to check your PyTorch version and ensure GPU availability if you plan to use it for faster computations.

In [ ]:
import torch
print(f"PyTorch Version: {torch.__version__}")

PyTorch Version: 2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## 2. Creating Tensors

Tensors are the fundamental data structure in PyTorch, similar to NumPy arrays. They can be created in various ways, initialized with specific values, or generated randomly.



### Initializing Tensors

PyTorch provides in built functions to create tensors with uninitialized values, zeros, ones, or random numbers.

In [ ]:
# torch.empty(shape): Creates a tensor with uninitialized data. The values will be whatever was in memory at the time.
print("Empty tensor:\n", torch.empty(2,3))

# torch.zeros(shape): Creates a tensor filled with zeros.
print("\nZeros tensor:\n", torch.zeros(2,3))

# torch.ones(shape): Creates a tensor filled with ones.
print("\nOnes tensor:\n", torch.ones(2,3))

# torch.rand(shape): Creates a tensor with random numbers from a uniform distribution between 0 and 1.
print("\nRandom tensor:\n", torch.rand(2,3))

Empty tensor:
 tensor([[1.7187e-04, 1.0324e-08, 5.1972e-08],
        [1.4580e-19, 1.1495e+24, 3.0881e+29]])

Zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random tensor:
 tensor([[0.6070, 0.5420, 0.0114],
        [0.7826, 0.9574, 0.6113]])


To ensure reproducibility of random tensors, you can use `torch.manual_seed()`. This sets the seed for the CPU, making random number generation deterministic.

In [ ]:
# Using torch.manual_seed for reproducibility
torch.manual_seed(100)
print("Random tensor with seed 100:\n", torch.rand(2,3))

# Calling rand again without resetting the seed will produce new random numbers
print("\nAnother random tensor without resetting seed:\n", torch.rand(2,3))

# Resetting the seed to the same value will produce the same sequence of random numbers again
torch.manual_seed(100)
print("\nRandom tensor after resetting seed to 100:\n", torch.rand(2,3))

Random tensor with seed 100:
 tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

Another random tensor without resetting seed:
 tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Random tensor after resetting seed to 100:
 tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [ ]:
# in different code cell
torch.manual_seed(100)
print("\nRandom tensor after resetting seed to 100:\n", torch.rand(2,3))


Random tensor after resetting seed to 100:
 tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


### Creating Tensors from Data

You can create tensors directly from Python lists or NumPy arrays using `torch.tensor()`.

In [ ]:
# Create a tensor from a Python list
my_list = [[1,2,3],[4,5,6]]
print("Tensor from list:\n", torch.tensor(my_list))

Tensor from list:
 tensor([[1, 2, 3],
        [4, 5, 6]])


### Specialized Tensor Creation Functions

PyTorch offers several functions for creating tensors with specific patterns, like sequences, identity matrices, or tensors filled with a constant value.

In [ ]:
# torch.arange(start, end, step): Returns a 1-D tensor of size `(end-start)/step` with values from `start` to `end` with `step`.
print("Using arange (0 to 10, step 2):", torch.arange(0,10,2))

# torch.linspace(start, end, steps): Returns a 1-D tensor of `steps` equally spaced points between `start` and `end`.
print("Using linspace (0 to 10, 10 steps):", torch.linspace(0,10,10))

# torch.eye(n): Returns a 2-D tensor with ones on the diagonal and zeros elsewhere (identity matrix).
print("Using eye (5x5 identity matrix):\n", torch.eye(5))

# torch.full(shape, fill_value): Creates a tensor of `shape` filled with `fill_value`.
print("Using full (3x3, filled with 5):\n", torch.full((3, 3), 5))

Using arange (0 to 10, step 2): tensor([0, 2, 4, 6, 8])
Using linspace (0 to 10, 10 steps): tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eye (5x5 identity matrix):
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full (3x3, filled with 5):
 tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## 3. Tensor Shapes

The shape of a tensor describes its dimensions. Understanding and manipulating tensor shapes is crucial for deep learning models.



### Inspecting Shape

You can get the shape of a tensor using the `.shape` attribute.

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
print("Original tensor x:\n", x)
print("Shape of x:", x.shape)

Original tensor x:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Shape of x: torch.Size([2, 3])


### Creating Tensors with Similar Shapes

PyTorch allows creating new tensors with the same shape as an existing tensor, often useful for creating masks or temporary storage.

In [ ]:
# torch.empty_like(input): Returns an uninitialized tensor with the same size as `input`.
print("Empty like x:\n", torch.empty_like(x))

# torch.zeros_like(input): Returns a tensor filled with zeros, with the same size as `input`.
print("\nZeros like x:\n", torch.zeros_like(x))

# torch.ones_like(input): Returns a tensor filled with ones, with the same size as `input`.
print("\nOnes like x:\n", torch.ones_like(x))

# torch.rand_like(input, dtype): Returns a tensor with random numbers from a uniform distribution, with the same size as `input`.
# You can also specify the dtype, e.g., torch.float32 for floating-point random numbers.
print("\nRandom like x (float32):\n", torch.rand_like(x, dtype=torch.float32))

Empty like x:
 tensor([[    132600456142224,          1043228064,                   0],
        [                  0,                   0, 7310593858020254331]])

Zeros like x:
 tensor([[0, 0, 0],
        [0, 0, 0]])

Ones like x:
 tensor([[1, 1, 1],
        [1, 1, 1]])

Random like x (float32):
 tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


## 4. Tensor Data Types

Each tensor has a specific data type (`dtype`) that determines the kind of values it can store (e.g., integers, floating-point numbers, booleans) and how much memory it consumes. Choosing the correct data type is important for memory efficiency and numerical precision.



### Checking and Assigning Data Types

You can check a tensor's data type using `.dtype` and assign a specific data type during creation or conversion.

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
print("Data type of x:", x.dtype)

# Assign data type during tensor creation
print("\nTensor with int32 dtype:", torch.tensor([1.0,2.0,3.0], dtype=torch.int32))
print("Tensor with float64 dtype:", torch.tensor([1,2,3], dtype=torch.float64))

# Convert a tensor to a different data type using .to()
print("\nTensor x converted to float32:\n", x.to(torch.float32))

### Detailed Data Type Reference



| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |

## 5. Mathematical Operations

PyTorch tensors support a wide range of mathematical operations, which can be categorized into scalar, element-wise, reduction, matrix, comparison, and special functions.

### Scalar Operations

Scalar operations involve performing an operation between a tensor and a single number (scalar). The operation is applied to every element of the tensor.

In [ ]:
x = torch.rand(2,2)
print("Original tensor x:\n", x)

print("\nAddition (x + 2):\n", x + 2)
print("Subtraction (x - 2):\n", x - 2)
print("Multiplication (x * 3):\n", x * 3)
print("Division (x / 3):\n", x / 3)
print("Integer Division ((x * 100) // 3):\n", (x * 100) // 3)
print("Modulo (((x * 100) // 3) % 2):\n", ((x * 100) // 3) % 2)
print("Power (x ** 2):\n", x**2)

### Element-Wise Operations

Element-wise operations apply a function or operation to each corresponding element of two tensors of the same shape.

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print("Tensor a:\n", a)
print("Tensor b:\n", b)

print("\nElement-wise addition (a + b):\n", a + b)
print("Element-wise subtraction (a - b):\n", a - b)
print("Element-wise multiplication (a * b):\n", a * b)
print("Element-wise division (a / b):\n", a / b)
print("Element-wise power (a ** b):\n", a ** b)
print("Element-wise modulo (a % b):\n", a % b)

Other common element-wise functions include absolute value, negation, rounding, ceiling, floor, and clamping.

In [ ]:
c = torch.tensor([1, -2, 3, -4])
print("Tensor c:\n", c)
print("Absolute value (torch.abs(c)):", torch.abs(c))
print("Negation (torch.neg(c)):", torch.neg(c))

d = torch.tensor([1.9, 2.3, 3.7, 4.4])
print("\nTensor d:\n", d)
print("Round (torch.round(d)):", torch.round(d))
print("Ceil (torch.ceil(d)):", torch.ceil(d))
print("Floor (torch.floor(d)):", torch.floor(d))
print("Clamp (torch.clamp(d, min=2, max=3)):", torch.clamp(d, min=2, max=3))

### Reduction Operations

Reduction operations reduce a tensor along one or more dimensions, resulting in a tensor with fewer dimensions (or a scalar). Common reductions include sum, mean, median, max, min, product, standard deviation, and variance.

In [ ]:
e = torch.randint(low=0, high=10, size=(2,3), dtype=torch.float32)
print("Tensor e:\n", e)

print("\nSum of all elements (torch.sum(e)):", torch.sum(e))
print("Sum along columns (dim=0):", torch.sum(e, dim=0))
print("Sum along rows (dim=1):", torch.sum(e, dim=1))

print("\nMean of all elements (torch.mean(e)):", torch.mean(e))
print("Mean along columns (dim=0):", torch.mean(e, dim=0))

print("\nMedian of all elements (torch.median(e)):", torch.median(e))

print("\nMaximum of all elements (torch.max(e)):", torch.max(e))
print("Minimum of all elements (torch.min(e)):", torch.min(e))

print("\nProduct of all elements (torch.prod(e)):", torch.prod(e))

print("\nStandard deviation of all elements (torch.std(e)):", torch.std(e))

print("\nVariance of all elements (torch.var(e)):", torch.var(e))

# argmax/argmin return the index of the maximum/minimum value
print("\nIndex of maximum value (torch.argmax(e)):", torch.argmax(e))
print("Index of minimum value (torch.argmin(e)):", torch.argmin(e))

### Matrix Operations

PyTorch supports standard linear algebra operations like matrix multiplication, dot product, transpose, determinant, and inverse.

In [ ]:
f = torch.randint(low=0, high=10, size=(2,3))
g = torch.randint(low=0, high=10, size=(3,2))

print("Tensor f (2x3):\n", f)
print("Tensor g (3x2):\n", g)

# Matrix multiplication (f * g) - the inner dimensions must match (3 in this case)
print("\nMatrix multiplication (torch.matmul(f, g)):\n", torch.matmul(f, g))

vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])
print("\nVector 1:", vector1)
print("Vector 2:", vector2)
# Dot product of two 1-D tensors
print("Dot product (torch.dot(vector1, vector2)):", torch.dot(vector1, vector2))

# Transpose: Swaps the dimensions of a tensor
# For a 2D tensor, it swaps rows and columns.
print("\nTranspose of f (torch.transpose(f, 0, 1)):\n", torch.transpose(f, 0, 1))

h = torch.randint(low=0, high=10, size=(3,3), dtype=torch.float32)
print("\nTensor h (3x3):\n", h)

# Determinant of a square matrix
print("Determinant of h (torch.det(h)):", torch.det(h))

# Inverse of a square matrix
# Note: The matrix must be invertible (non-singular).
print("Inverse of h (torch.inverse(h)):\n", torch.inverse(h))

### Comparison Operations

Comparison operations perform element-wise comparisons between two tensors or a tensor and a scalar, returning a boolean tensor.

In [ ]:
i = torch.randint(low=0, high=10, size=(2,3))
j = torch.randint(low=0, high=10, size=(2,3))

print("Tensor i:\n", i)
print("Tensor j:\n", j)

print("\nGreater than (i > j):\n", i > j)
print("Less than (i < j):\n", i < j)
print("Equal to (i == j):\n", i == j)
print("Not equal to (i != j):\n", i != j)
# Add more comparison operations as needed, e.g., >=, <=

### Special Functions

PyTorch also includes various special mathematical functions commonly used in deep learning, such as logarithmic, exponential, square root, sigmoid, softmax, and ReLU.

In [ ]:
k = torch.randint(low=0, high=10, size=(2,3), dtype=torch.float32)
print("Tensor k:\n", k)

# Natural logarithm
# Note: log(0) is -inf, so input tensor should ideally contain positive values.
print("\nLogarithm (torch.log(k)):\n", torch.log(k))

# Exponential
print("\nExponential (torch.exp(k)):\n", torch.exp(k))

# Square root
print("\nSquare Root (torch.sqrt(k)):\n", torch.sqrt(k))

# Sigmoid activation function
print("\nSigmoid (torch.sigmoid(k)):\n", torch.sigmoid(k))

# Softmax activation function (usually along a dimension)
print("\nSoftmax along dim=0 (torch.softmax(k, dim=0)):\n", torch.softmax(k, dim=0))

# Rectified Linear Unit (ReLU) activation function
print("\nReLU (torch.relu(k)):\n", torch.relu(k))

## 6. Inplace Operations



Inplace operations are operations that modify the tensor in place without creating a new one. They are typically denoted by a trailing underscore (e.g., `add_`, `relu_`). This can be memory efficient, but be cautious as it directly changes the original tensor.

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print("Original tensor m:\n", m)
print("Original tensor n:\n", n)

# Inplace addition: m is modified
m.add_(n)
print("\nm after m.add_(n):\n", m)
print("Tensor n (unchanged):\n", n)

# Non-inplace ReLU: returns a new tensor, m is unchanged
print("\nNon-inplace ReLU (torch.relu(m)):\n", torch.relu(m))
print("Tensor m (still original values):\n", m)

# Inplace ReLU: m is modified
m.relu_()
print("\nm after m.relu_():\n", m)

## 7. Copying a Tensor

Understanding how tensors are copied is crucial to avoid unintended side effects. Simply assigning one tensor to another (`b = a`) creates a new reference to the *same* underlying data, while `clone()` creates a new tensor with a copy of the data.

In [ ]:
a = torch.rand(2,3)
print("Original tensor a:\n", a)

# Case 1: Simple assignment (creates a view/reference)
b = a
print("\nTensor b (assigned from a):\n", b)

# Modifying 'a' will also modify 'b' because they point to the same memory
a[0][0] = 0
print("\na after modifying a[0][0]:\n", a)
print("b after modifying a[0][0]:\n", b)

# Check memory addresses to confirm they are the same object
print("\nID of a (memory address):", id(a))
print("ID of b (memory address):", id(b))

# Case 2: Cloning (creates a deep copy)
b = a.clone()
print("\na after cloning:\n", a)
print("b after cloning:\n", b)

# Now, modifying 'a' will NOT modify 'b'
a[0][0] = 10
print("\na after modifying a[0][0] again:\n", a)
print("b after modifying a[0][0] again (unchanged):\n", b)

# Check memory addresses to confirm they are different objects
print("\nID of a (memory address):", id(a))
print("ID of b (memory address):", id(b))

In [ ]:
import torch
print(torch.__version__)

In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

## Creating a Tensor

In [ ]:
# using empty
a = torch.empty(2,3)

In [ ]:
# check type
type(a)

In [ ]:
# using zeros
torch.zeros(2,3)

In [ ]:
# using ones
torch.ones(2,3)

In [ ]:
# using rand
torch.rand(2,3)

In [ ]:
# use of seed
torch.rand(2,3)

In [ ]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

## Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

In [ ]:
x.shape

In [ ]:
torch.empty_like(x)

In [ ]:
torch.zeros_like(x)

In [ ]:
torch.ones_like(x)

In [ ]:
torch.rand_like(x, dtype=torch.float32)

## Tensor Data Types

In [ ]:
# find data type
x.dtype

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

### 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

In [ ]:
# negative
torch.neg(c)

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

In [ ]:
# ceil
torch.ceil(d)

In [ ]:
# floor
torch.floor(d)

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

### 3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

In [ ]:
# median
torch.median(e)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

In [ ]:
# product
torch.prod(e)

In [ ]:
# standard deviation
torch.std(e)

In [ ]:
# variance
torch.var(e)

In [ ]:
# argmax
torch.argmax(e)

In [ ]:
# argmin
torch.argmin(e)

### 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

In [ ]:
# matrix multiplcation
torch.matmul(f, g)

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

In [ ]:
# determinant
torch.det(h)

In [ ]:
# inverse
torch.inverse(h)

### 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

In [ ]:
# log
torch.log(k)

In [ ]:
# exp
torch.exp(k)

In [ ]:
k

In [ ]:
# sqrt
torch.sqrt(k)

In [ ]:
# sigmoid
torch.sigmoid(k)

In [ ]:
# softmax
torch.softmax(k, dim=0)

In [ ]:
# relu
torch.relu(k)

## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

In [ ]:
m.add_(n)

In [ ]:
m

In [ ]:
n

In [ ]:
torch.relu(m)

In [ ]:
m.relu_()

In [ ]:
m

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

In [ ]:
b = a

In [ ]:
b

In [ ]:
a[0][0] = 100

In [ ]:
a

In [ ]:
b

In [ ]:
id(a)

In [ ]:
id(b)

In [ ]:
b = a.clone()

In [ ]:
a

In [ ]:
b

In [ ]:
a[0][0] = 10

In [ ]:
a

In [ ]:
b

In [ ]:
id(a)

In [ ]:
id(b)